In [28]:
import numpy as np #2005 by Travis Oliphant

In [29]:
np.__version__

'1.25.2'

In [30]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [31]:
#Why numpy
#-mathematical function
#Faster

In [32]:
l = [1, 2, 3, 4, 5]

In [33]:
arr = np.array(l)

In [34]:
arr

array([1, 2, 3, 4, 5])

In [35]:
type(np.array(l))

numpy.ndarray

In [36]:
type(np.array(l))

numpy.ndarray

In [37]:
arr.ndim # to print the dimension of an array, here it is 1d array so it gives output 1

1

In [38]:
l = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U21')

In [39]:
arr.ndim

1

In [40]:
arr

array([1, 2, 3, 4, 5])

In [41]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # no. of brackets will tell you if its a 1d 2d or a 3d array
                                        # here 2 brackets are present in begining so its a 2d array

In [42]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr1.ndim

2

In [44]:
l = [1, 2, 3, 4]

In [45]:
np.array(l)

array([1, 2, 3, 4])

In [46]:
mat = np.matrix(l) #matris will be by default 2d

In [47]:
np.matrix([[1, 2], [5, 6], [7, 8]])

matrix([[1, 2],
        [5, 6],
        [7, 8]])

In [48]:
np.array([[[1, 2], [5, 6], [7, 8]]]) # here there are 3 brackets in begining, so its a 3d

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [49]:
#more way to convert list to array
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [50]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [51]:
mat

matrix([[1, 2, 3, 4]])

In [52]:
np.asanyarray(mat) # as matrix is a subclass of an array(just like 2d array), hence it will pass matrix itself(asanyarray())

matrix([[1, 2, 3, 4]])

In [53]:
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [54]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [55]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [56]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a = 5
np.array(a)

array(5)

In [58]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [59]:
a = arr

In [60]:
a

array([1, 2, 3, 4, 5])

In [61]:
arr[0] = 1000

In [62]:
arr

array([1000,    2,    3,    4,    5])

In [63]:
a

array([1000,    2,    3,    4,    5])

In [64]:
a

array([1000,    2,    3,    4,    5])

In [65]:
b = a.copy()
b[0] = 2000

In [66]:
b

array([2000,    2,    3,    4,    5])

In [67]:
a

array([1000,    2,    3,    4,    5])

In [68]:
#to create array >> .array, .asasrray, .asanyarray, deep copy, shallow copy

In [69]:
#There are multiple ways to generating arrays: fromfunction, fromiter, fromstring

In [70]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [71]:
arr

array([1000,    2,    3,    4,    5])

In [72]:
arr.shape

(5,)

In [73]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr1.shape

(2, 3)

In [75]:
arr.size

5

In [76]:
arr1.size

6

In [77]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [78]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [79]:
for i in range(5):
    print(i)

0
1
2
3
4


In [80]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [81]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [82]:
list(range(5))

[0, 1, 2, 3, 4]

In [83]:
iterable = (i*i for i in range(5))

In [84]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [85]:
np.fromstring('23 34 67', sep = ' ') # sep = seperator will seperate every digit with space

array([23., 34., 67.])

In [86]:
np.fromstring('23,34,67', sep = ',') # will seperate every digit with a comma

array([23., 34., 67.])

In [87]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')

<ipython-input-87-11e9461867a2>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [88]:
arr

array([1000,    2,    3,    4,    5])

In [89]:
arr.size

5

In [90]:
arr.shape

(5,)

In [91]:
arr.dtype

dtype('int64')

In [92]:
l = [1, 2,3, "Ajay"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [93]:
arr

array(['1', '2', '3', 'Ajay'], dtype='<U21')

In [94]:
list(range(5))

[0, 1, 2, 3, 4]

In [95]:
range(5)

range(0, 5)

In [96]:
list(range(1.0, 2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [97]:
list(np.arange(0.1, 10.2, 0.1)) #(start, stop, jump) # as range cannot function with decimals, arange was made. it also includes upper bound.

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [98]:
np.linspace(1, 5, 10) # syntax: (start, stop , no. of values to generate in between 1-5), it will include upper-bound 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [99]:
np.logspace(1, 5, 10, base = 2) # syntax: (start, stop, no. of values, log base)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [100]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [101]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [102]:
arr1

array([0., 0., 0., 0., 0.])

In [103]:
arr1.ndim

1

In [104]:
arr2 = np.zeros((3, 4))
arr2.shape

(3, 4)

In [105]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
arr2.ndim

2

In [107]:
arr3 = np.zeros((3, 3, 4)) # syntax: repeat 3x4 array in 3d-axis
arr3.shape

(3, 3, 4)

In [108]:
arr3.ndim # will give dimension of an array, here it is a 3d array

3

In [109]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [116]:
arr4 = np.zeros((1, 3, 3, 4)) # styntax: (one outer dimension, one inner 3d dimention, rows, columns )
arr4.shape

(1, 3, 3, 4)

In [117]:
arr4.ndim

4

In [118]:
arr4 # we can see 4 brackets so it's 4 dimension array

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [119]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
arr = np.ones((3,4))

In [121]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [123]:
arr * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
np.array([[[[[[[[[[[[[[1, 1, 1, 1, ,1 ]]]]]]]]]]]]]])

In [124]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
l = [1, 2,3, 4,5, "Prince"]
arr = np.array(l)
arr.dtype

In [ ]:
arr